"""initial schema

Bootstrap migration. Creates all tables defined on `Base.metadata` (users,
workflows, credentials, executions). All subsequent migrations are
hand-authored or autogenerated and target schema deltas only.

Revision ID: 0001
Revises:
Create Date: 2026-05-25
"""
from typing import Sequence, Union

from alembic import op

from db.database import Base
import models.user  # noqa: F401
import models.workflow  # noqa: F401
import models.credentials  # noqa: F401
import models.execution  # noqa: F401

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
